# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'apex-stat-tracker' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for apex-stat-tracker

  # add the Firebase pod for Google Analytics
  pod 'Firebase/Analytics'
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'
  pod 'FirebaseFirestoreSwift'
  # add pods for any other desired Firebase products
  # https://firebase.google.com/docs/ios/setup#available-pods

  target 'apex-stat-trackerTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'apex-stat-trackerUITests' do
    # Pods for testing
  end

end
